# Generated by Django 5.2.7 on 2025-10-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('trabajador', 'Trabajador'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
