# Generated by Django 5.2.7 on 2025-10-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='confirmado',
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_APROBACION', 'Pendiente de aprobación'), ('APROBADA', 'Aprobada'), ('PENDIENTE_PAGO', 'Pendiente de pago'), ('PAGO_COMPLETO', 'Pago completo'), ('ANULADA', 'Anulada')], default='PENDIENTE_APROBACION', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_reservar_sin_adelanto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'Rechazado'), ('DEVUELTO', 'Devuelto')], default='PENDIENTE', max_length=15),
        ),
    ]
