# Generated by Django 5.2.7 on 2025-10-29 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_reserva_confirmado_reserva_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancha',
            options={},
        ),
        migrations.AlterField(
            model_name='pago',
            name='verificado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['trabajador', 'administrador']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_APROBACION', 'Pendiente de aprobación'), ('APROBADA', 'Aprobada'), ('PAGO_COMPLETO', 'Pago completo'), ('ANULADA', 'Anulada')], default='PENDIENTE_APROBACION', max_length=20),
        ),
    ]
