# Generated by Django 5.2.7 on 2025-10-31 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_cancha_options_alter_pago_verificado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='reservas.reserva'),
        ),
    ]
