# Generated by Django 5.2.7 on 2025-10-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_reserva_monto_total_alter_pago_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
