# Generated by Django 5.2.7 on 2025-10-31 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_pago_observacion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_reserva_por_hora',
        ),
    ]
